from selenium.webdriver.common.by import By


LOGIN_REGISTER_BUTTON = (By.XPATH, ".//button[contains(text(), 'Вход и регистрация')]")
NO_ACCOUNT_BUTTON = (By.XPATH, ".//button[contains(text(), 'Нет аккаунта')]")
EMAIL_INPUT = (By.NAME, "email")
PASSWORD_INPUT = (By.NAME, "password")
REPEAT_PASSWORD_INPUT = (By.NAME, "submitPassword")
CREATE_ACC_BUTTON = (By.CSS_SELECTOR, "button.buttonPrimary.inButtonText[style*='max-width: 192px']")
USER_AVATAR = (By.CSS_SELECTOR, "button.circleSmall")
USER_NAME = (By.XPATH, ".//h3[contains(@class, 'name') and text()='User.']")
EMAIL_ERROR = (By.XPATH, ".//span[contains(text(), 'Ошибка')]")
LOGIN_BUTTON = (By.XPATH, ".//button[text()='Войти']")
LOGOUT_BUTTON = (By.XPATH, ".//button[contains(text(), 'Выйти')]")
CREATE_AD_BUTTON = (By.XPATH, ".//button[contains(text(), 'Разместить объявление')]")
PUBLISH_AD_BUTTON = (By.XPATH, ".//button[contains(text(), 'Опубликовать')]")
TITLE = (By.XPATH, ".//input[@placeholder='Название']")
DESCRIPTION = (By.XPATH, "//textarea[@placeholder='Описание товара']")
PRICE = (By.XPATH, ".//input[@placeholder='Стоимость']")
RADIO_BUTTON = (By.CLASS_NAME, "radioUnput_inputRegular__FbVbr")
DROPDOWN_CATEGORY = (By.XPATH, ".//button[contains(@class, 'dropDownMenu_arrowDown')]")
CATEGORY_TECH = (By.XPATH, ".//span[text()='Технологии']")
DROPDOWN_CITY = (By.XPATH, "(.//button[contains(@class, 'dropDownMenu_arrowDown')])[2]")
CITY_SPB = (By.XPATH, ".//span[text()='Санкт-Петербург']")
ADS__SECTION =(By.XPATH, ".//h1[text()='Мои объявления']")
AD_TITLE = "(//div[@class='about']/h2[contains(text(), '{}')])[1]"
MODAL_WINDOW =(By.XPATH, ".//h1[contains(text(), 'Чтобы разместить объявление, авторизуйтесь')]")
EMAIL_INPUT_BY_NAME = (By.NAME, "email")
PASSWORD_INPUT_BY_NAME = (By.NAME, "password")
SUBMIT_PASSWORD_INPUT_BY_NAME = (By.NAME, "submitPassword")
PARENT_DIV_BY_XPATH = (By.XPATH, "./parent::div")